services:
  ## ---------------------------------------------------------------------------------- PostgreSQL ----------------------------------------------------------------------------------
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql